# version: "3.9"
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - mongo

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./frontend:/app
#     environment:
#       - VITE_API_URL=http://backend:8000
#     depends_on:
#       - backend

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
