# # Use official Node image
# FROM node:18

# # Set working directory
# WORKDIR /app

# # Copy package files first (for caching)
# COPY package.json package-lock.json* ./

# # Install dependencies
# RUN npm install

# # Copy all frontend files
# COPY . .

# # Expose Vite dev server port
# EXPOSE 5173

# # Run frontend
# CMD ["npm", "run", "dev"]
